domain_name = "davidpeach.me"
droplet_image = "ubuntu-24-04-x64"
droplet_name = "davidpeach.me"
droplet_region = "ams3"
droplet_size = "s-1vcpu-512mb-10gb"
ssh_key_name = "davidpeachdotme"
ssh_local_path = "~/.ssh/id_ed25519_zet.pub"
a_record_name = "@"
